### ISSUE TITLE
Having latest block hash already available at time of order submission

### ISSUE THREAD

**Issue by arniwesth** [bmresearch/Solnet.Mango#103]
In all the examples I have seen so far, order submissions first requires making a request for the latest/recent block hash, eg here:

https://docs.mango.markets/development-resources/client-libraries#post-orders

This seems potentially inefficient. Is there a way to subscribe to latest block hash so it would be available at order submission time? I could create a task requesting it at a reasonable frequency, but not sure if that would be best practice.

**Comment by murlokito** [comment]
Unfortunately there's no reliable way to subscribe to [block hashes](https://docs.solana.com/developing/clients/jsonrpc-api#blocksubscribe---unstable-disabled-by-default) as the pubsub channel is still considered unstable and is disabled by default.

Running a background task which periodically fetches the block hash is something I've done before, but there's a few things to consider, for example, if by any chance you end up reusing the same block hash you must guarantee that the transaction payload differs in some way, otherwise the transaction will be considered duplicate and will be rejected by most RPCs.

**Comment by arniwesth** [comment]
Thanks for the info.
