### ISSUE TITLE
[Bug] Cannot connect to devnet

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [bmresearch/Solnet.Mango#24]
**To Reproduce**
Pick any example like
https://github.com/bmresearch/Solnet.Mango/blob/master/Solnet.Mango.Examples/GetMangoAccountExample.cs

And switch MainNet to DevNet

Error message:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Solnet.Mango.BaseClient.GetAccount[T](String accountAddress, Commitment commitment)
   at Solnet.Mango.MangoClient.GetMangoGroupAsync(String account, Commitment commitment)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Solnet.Mango.MangoClient.GetMangoGroup(String account, Commitment commitment)
   at SimpleTrader.GetMangoAccountExample.Run() in D:\Code\Crypto\SimpleTrader\SimpleTrader\GetMangoAccountExample.cs:line 29
   at SimpleTrader.Program.TestMango() in D:\Code\Crypto\SimpleTrader\SimpleTrader\Program.cs:line 31
   at SimpleTrader.Program.Main() in D:\Code\Crypto\SimpleTrader\SimpleTrader\Program.cs:line 25
   at SimpleTrader.Program.<Main>()
```

**Comment by murlokito** [comment]
Hey @SpaceMonkeyForever, thanks for reporting this. The mango program implementation here is defaulting to MainNet and currently there's no way to switch to test/devnet despite changing the `RpcClient` cluster, we're working on making this a possibility in other program implementations in the main library and as soon as we have an intuitive way of doing this it will also be added here and to the Serum library.

**Comment by SpaceMonkeyForever** [comment]
Thank you. I really appreciate your work on this. The only libraries available right now are the official TS client, mango-explorer (Python) and this client. C#/dotnet is a far better choice compared to those two other options, so I really hope I can use this client instead of having to use the Python client for now.

**Comment by murlokito** [comment]
Are you looking to use first on testnet/devnet and then migrating to mainnet usage? I could give you some pointers on how we're thinking about doing this if you'd like to help and maybe submit a PR.

I know there's also a few other issues in the lib wrt calculating account equity and some other things when there are several perps positions open and stuff (it messes up the math and I haven't really figured out where the bug is despite countless hours of debugging it).

**Comment by SpaceMonkeyForever** [comment]
Yes, I have to test my idea on devnet first. To be honest, at the moment, I'm focused on getting the main logic done in Python as fast as possible as a prototype/PoC then I will work on rewriting it dotnet/Rust to make it robust. It would be fun to help you and submit a PR tho

**Comment by murlokito** [comment]
We were using the program classes as being static for pretty much everything, but recently in order to accomodate testnet and devnet we made some changes to Solnet by adding a `BaseProgram` class that all program implementations should subclass, and then you'd instantiate the program class by passing it the program id key of the program you want to use [like this](https://github.com/bmresearch/Solnet/blob/60c6f947ae1d739c3404f224c3e67e0831798fd3/src/Solnet.Programs/Governance/GovernanceProgram.cs#L69).

This way you would need to instantiate the program, yes, but you could do something like 
```csharp
var mangoProgram = new MangoProgram(MangoProgram.TestNetProgramIdKey)
```

to be able to do this, the library needs to undergo some refactoring because the instructions always refers to the static program id key for mango v3 as it is [here](https://github.com/bmresearch/Solnet.Mango/blob/master/Solnet.Mango/MangoProgram.cs#L96). I know I abstracted it with the overloads but ideally that wouldn't be the case and you wouldn't need to pass in the program id because you have already instantiated the class for the specific program (and network) you want.

The same thing goes for the `MangoClient`, it's defaulting to use the mango v3 program id key from mainnet [here](https://github.com/bmresearch/Solnet.Mango/blob/master/Solnet.Mango/MangoClient.cs#L175), we should change this to take in the program id key on the client factory.

If you'd like to try to help with this do tell me, maybe I can give you some more pointers/ideas/snippets, and any question feel free to ask

**Comment by murlokito** [comment]
@SpaceMonkeyForever this issue has been resolved with the latest updates to the library, a lot of things were fixed (errors in health/equity calculations, bunch of decoding errors that were still hanging around etc), there were also new instructions added (some of these are still untested, like the ones for advanced orders) and you now have the ability to use this on devnet (a lot of the tests added by the test suite were done on devnet)

going to close this and ship v0.1 which is way more robust than it was previously, enjoy the fixes and if anything else comes up feel free to open an issue :)
